name: "HA Automation Helper"
version: "1.0.2"
slug: "ha_automation_helper"
description: "基于 Home Assistant WebSocket API 的智能家居控制面板"
url: "https://github.com/your-username/ha-automation-helper"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:home-automation
panel_title: "HA Automation"
panel_admin: true
startup: application
boot: auto
map:
  - config:rw
options: {}
schema: {}
webui: "http://[HOST]:[PORT:8099]"
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web 界面 (不需要配置 - 使用 Ingress)" 
